# Toolchain file for the Buildroot aarch64 SDK used by the CLion aarch64 profile.
#
# Configure with:
#   cmake -S . -B build-aarch64 \
#     -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/aarch64-buildroot.cmake \
#     -DCMAKE_BUILD_TYPE=Release

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(SIGNLANG_AARCH64_SDK_ROOT "/opt/aarch64-buildroot-linux-gnu_sdk-buildroot"
    CACHE PATH "Root directory of the Buildroot aarch64 SDK")
set(SIGNLANG_AARCH64_TARGET_TRIPLE "aarch64-buildroot-linux-gnu"
    CACHE STRING "Buildroot aarch64 target triple")

set(SIGNLANG_AARCH64_SDK_BIN "${SIGNLANG_AARCH64_SDK_ROOT}/bin")
set(CMAKE_SYSROOT
    "${SIGNLANG_AARCH64_SDK_ROOT}/${SIGNLANG_AARCH64_TARGET_TRIPLE}/sysroot"
    CACHE PATH "Buildroot aarch64 sysroot")

set(CMAKE_C_COMPILER "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-g++")

set(CMAKE_AR "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-ar")
set(CMAKE_RANLIB "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-ranlib")
set(CMAKE_NM "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-nm")
set(CMAKE_OBJCOPY "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-objcopy")
set(CMAKE_OBJDUMP "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-objdump")
set(CMAKE_READELF "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-readelf")
set(CMAKE_STRIP "${SIGNLANG_AARCH64_SDK_BIN}/${SIGNLANG_AARCH64_TARGET_TRIPLE}-strip")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
